<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{{ title }}</title>
    <link rel="stylesheet" href="/stylesheets/style.css">
    <script src="/js/zepto.js" type="text/javascript" ></script>
    <script src="/js/index.js" type="text/javascript" ></script>

</head>
<body>

  <div class="one btn">
  </div>
  <div class="two btn">
  </div>
  <div class="three btn">
  </div>
  <div class="four btn">
  </div>
</body>
</html>
